### ISSUE TITLE
Cannot compile on macOS ARM

### ISSUE THREAD

**Issue by maxcountryman** [caiiiycuk/postgresql-to-sqlite#14]
```
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:429)
        at sbt.TrapExit$.installManager(TrapExit.scala:52)
        at sbt.StandardMain$.runManaged(Main.scala:60)
        at sbt.xMain.run(Main.scala:35)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release```

**Comment by caiiiycuk** [comment]
Hmm, is [binary](https://github.com/caiiiycuk/postgresql-to-sqlite/releases) version works for you?
