### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Dot3xe** [caiiiycuk/postgresql-to-sqlite#4]
`[info] Loading project definition from /Users/nicolas/Downloads/postgresql-to-sqlite/project
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1262)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
	at sbt.IO$.pathSplit(IO.scala:727)
	at sbt.IO$.parseClasspath(IO.scala:825)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:64)
	at sbt.compiler.AggressiveCompile.withBootclasspath(AggressiveCompile.scala:51)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:84)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:71)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:46)
	at sbt.Compiler$.apply(Compiler.scala:75)
	at sbt.Compiler$.apply(Compiler.scala:66)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:770)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (compile:compile) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
`

**Comment by caiiiycuk** [comment]
sbt one-jar works fine for me

**Comment by Dot3xe** [comment]
So strange ...
I am compiling in mac os, maybe there is some extra steps involved ?

**Comment by caiiiycuk** [comment]
Sorry, don't know. I never used mac, but I built it for you. Now you can download jar from releases page on github:
https://github.com/caiiiycuk/postgresql-to-sqlite/releases/tag/1.0

if it works for you, please close the issue

**Comment by Dot3xe** [comment]
Works Good !
